title: "I Am WIP"
description: "Progress without pressure."
url: "https://iamwip.blog"

# Use Minimal Mistakes via GitHub Pages
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Basic author card on posts
author:
  name: "Nithin Murali"
  bio: "Founder, I Am WIP — exploring continuous improvement without burnout."

# Defaults for blog posts
defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

# Pagination (optional)
paginate: 6
paginate_path: "/page:num/"
