title: "I Am WIP"
description: "Progress without pressure."
url: "https://iamwip.blog"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

